{
    "extras": [ {
        "file": "diminish.el",
        "src": "http://www.eskimo.com/~seldon/diminish.el"
    }, {
        "file": "dirvars.el",
        "src": "http://www.emacswiki.org/emacs/download/dirvars.el"
    }, {
        "file": "fscroll.el",
        "src": "http://www.davep.org/emacs/fscroll.el"
    }, {
        "file": "indent-tabs-maybe.el",
        "src": "http://www.loveshack.ukfsn.org/emacs/indent-tabs-maybe.el"
    }, {
        "file": "paredit-21.el",
        "src": "http://mumble.net/~campbell/emacs/paredit-21.el"
    }, {
        "file": "pcmpl-rake.el",
        "src": "http://github.com/technomancy/emacs-starter-kit/raw/master/elpa-to-submit/pcmpl-rake.el"
    }, {
        "file": "redo.el",
        "src": "http://www.wonderworks.com/download/redo.el"
    } ],
    "tools": [ {
        "file": "boxquote.el",
        "src": "http://www.davep.org/emacs/boxquote.el"
    }, {
        "file": "browse-kill-ring.el",
        "src": "http://www.emacswiki.org/emacs/download/browse-kill-ring.el"
    }, {
        "file": "ell.el",
        "src": "http://www.damtp.cam.ac.uk/user/eglen/emacs/ell.el"
    }, {
        "file": "htmlize.el",
        "src": "http://fly.srk.fer.hr/~hniksic/emacs/htmlize.el"
    }, {
        "file": "igrep.el",
        "src": "http://www.emacswiki.org/emacs/download/igrep.el"
    }, {
        "file": "itunes.el",
        "src": "http://www.emacswiki.org/emacs/download/itunes.el"
    }, {
        "file": "osx-plist.el",
        "src": "http://edward.oconnor.cx/elisp/osx-plist.el"
    }, {
        "file": "pastie.el",
        "src": "http://www.emacswiki.org/emacs/download/pastie.el"
    }, {
        "file": "ri.el",
        "src": "http://github.com/technomancy/emacs-starter-kit/raw/master/elpa-to-submit/ri.el"
    }, {
        "file": "thinks.el",
        "src": "http://www.davep.org/emacs/thinks.el"
    }, {
        "file": "xcscope.el",
        "src": "http://cscope.cvs.sourceforge.net/viewvc/*checkout*/cscope/cscope/contrib/xcscope/xcscope.el"
    } ],
    "modes": [ {
        "file": "applescript-mode.el",
        "src": "http://sourceforge.jp/projects/macemacsjp/svn/view/applescript-mode/trunk/applescript-mode.el?view=co&root=macemacsjp"
    }, {
        "file": "espresso.el",
        "src": "http://download.savannah.gnu.org/releases-noredirect/espresso/espresso.el"
    }, {
        "file": "f-script-mode.el",
        "src": "http://web.mac.com/oyasuhisa/Products/F-Script_files/f-script-mode.el.gz"
    }, {
        "file": "gambit.el",
        "src": "http://www.iro.umontreal.ca/~gambit/repo/.cgit.cgi/Gambit/plain/misc/gambit.el"
    }, {
        "file": "go-mode.el",
        "src": "http://go.googlecode.com/hg/misc/emacs/go-mode.el?r=release"
    }, {
        "file": "google-c-style.el",
        "src": "http://google-styleguide.googlecode.com/svn/trunk/google-c-style.el"
    }, {
        "file": "hen.el",
        "src": "http://www.call-with-current-continuation.org/hen.el"
    }, {
        "file": "hs-lint.el",
        "src": "http://xtalk.msk.su/~ott/common/emacs/hs-lint.el"
    }, {
        "file": "io-mode.el",
        "src": "http://github.com/stevedekorte/io/raw/master/extras/SyntaxHighlighters/Emacs/io-mode.el"
    }, {
        "file": "ipython.el",
        "src": "http://ipython.scipy.org/dist/ipython.el"
    }, {
        "file": "pod-mode.el",
        "src": "http://search.cpan.org/src/SCHWIGON/pod-mode-0.5/pod-mode.el"
    }, {
        "file": "rdoc-mode.el",
        "src": "http://svn.ruby-lang.org/repos/ruby/trunk/misc/rdoc-mode.el"
    }, {
        "file": "rst.el",
        "src": "http://svn.berlios.de/viewcvs/*checkout*/docutils/trunk/docutils/tools/editors/emacs/rst.el"
    }, {
        "file": "ruby-electric.el",
        "src": "http://svn.ruby-lang.org/repos/ruby/trunk/misc/ruby-electric.el"
    }, {
        "file": "scheme-complete.el",
        "src": "http://synthcode.com/emacs/scheme-complete-0.8.9.el.gz"
    }, {
        "file": "scheme48.el",
        "src": "http://www.emacswiki.org/emacs/download/scheme48.el"
    }, {
        "file": "textile-mode.el",
        "src": "http://github.com/technomancy/emacs-starter-kit/raw/master/elpa-to-submit/textile-mode.el"
    }, {
        "file": "treetop.el",
        "src": "http://github.com/hornbeck/public_emacs/raw/master/treetop.el"
    }, {
        "file": "yaml-mode.el",
        "src": "http://github.com/yoshiki/yaml-mode/raw/master/yaml-mode.el"
    } ]
}
