
;; Load packages from the `vendor' subdirectory
(let* ((vendor-dir (file-name-as-directory (concat dot-emacs-dir "vendor")))
       (non-hidden (rx bos (not (in ".")))))
  (dolist (path (directory-files vendor-dir 'full non-hidden))
    (let* ((path (file-name-as-directory path))
           (lisp-path (file-name-as-directory (concat path "lisp")))
           (docs-path (file-name-as-directory (concat path "doc")))
           (info-path (file-name-as-directory (concat docs-path "info")))
           (autoloads (concat path "autoloads")))
      (add-to-list 'load-path path)
      (add-to-list 'load-path lisp-path)
      (load autoloads 'noerror)
      (dolist (info-dir (list info-path docs-path path))
        (when (file-exists-p (concat info-dir "dir"))
          (add-to-list 'Info-additional-directory-list info-dir)
          (return))))))
